//
//  LocationManager.swift
//  Hunger
//
//  This class deals with emanaging user locations: tracking of local and others users locations and collision detection between them.
//
//  Adapted from https://stackoverflow.com/questions/56533059/how-to-get-current-location-with-swiftui by Roman Reimche on 13.10.19.
//  Copyright © 2019 Roman Reimche. All rights reserved.
//

import Foundation
import Combine
import CoreLocation
import Firebase
import GeoFire


// TODO find a way for LocationManager to start providing locations only when asked to.
class LocationManager: NSObject, CLLocationManagerDelegate, ObservableObject {
    
    let defaultStartingLocation = CLLocation(latitude: 0, longitude: 0)
    private let manager: CLLocationManager 
    private var rdbRef: DatabaseReference!
    private let fdbManager = FirestoreManager()
    private var geoFire: GeoFire!
    private var session: SessionStore!
    private var circleQuery: GFCircleQuery?
    private var circleQueryHandles: Array<FirebaseHandle> = []
    private let databasePath = "players-online"
    private let circleQueryRadius: Double = 10 // in kilometers
    
    // Distance at which two users are thought to collide
    let collisionDistance: Double = 5 // in meters
    var zombieCollidedWithHuman = false
    
    // MARK: ObservableObject
    
    
    //@Published var lastKnownLocation: CLLocation? don't need to update map view on this, because it is update by user tracking
    var lastKnownLocation: CLLocation?
    typealias DistanceToUser = CLLocationDistance
    @Published var nearbyPlayers : Dictionary<FbUid, (User, DistanceToUser)> = [:]

    // MARK: INIT
    
    init(manager: CLLocationManager = CLLocationManager(), session: SessionStore) {
        
        self.manager = manager
        self.rdbRef = Database.database().reference()
        self.geoFire = GeoFire(firebaseRef: rdbRef)
        self.session = session
        //self.lastKnownLocation = CLLocation(latitude: 0, longitude: 0)
        
        super.init()
        
        // Start updating location
        self.manager.delegate = self
        self.manager.requestWhenInUseAuthorization()
        
        
    }
    
    // MARK: Go online/offline
    
    private func startUpdatingLocations(){
        self.manager.startUpdatingLocation()
        
        // Suscribe for events generated by nearby online users (radius is in Kilometers)
        self.circleQuery = self.geoFire.query(at: lastKnownLocation ?? defaultStartingLocation, withRadius: circleQueryRadius)

        // Set event processors for the events of other players entering and leayving
        // the nearby zone and for moving inside of it.
        let gfEventProcessors : Dictionary<GFEventType, gfEventProcessor> =
            [.keyEntered : keyEnteredProcessor(key:enteredUserLocation:),
             .keyMoved : keyMovedProcessor(key:movedUserLocation:),
             .keyExited : keyExitedProcessor(key:exitedUserLocation:) ]
        for (eventType, processor) in gfEventProcessors {
            self.circleQueryHandles.append(circleQuery!.observe(eventType, with: processor))
        }
    }
    
    private func stopUpdatingLocations(){
        // TODO stop updating location service and geofire
        self.circleQuery!.removeAllObservers()
        self.manager.stopUpdatingLocation()
    }
    
    
    func goOnline(){
        startUpdatingLocations()
    }
    
    func goOffline(){
        stopUpdatingLocations()
        rdbRef.child(databasePath + "/" + session.user!.uid).removeValue()
        geoFire.removeKey(session.user!.uid)
    }
    
    // MARK: CLLocationManagerDelegate

    func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
        //print(locations)
        
        guard session.user != nil else {
            print("Warning: StorageSession.user is nil in LocationManager.locationmanager(_:didUpdateWithOptions). The update will not be processed.")
            return
        }
        
        guard session.user!.playsAs != nil else {
            print("Warning: LocationManager.locationManager(manager:didUpdateLocations:) was called before local user player type was set. The update will not be processed.")
            return
        }
        
        guard self.circleQuery != nil else {
            print("Warning: LocationManager.circleQuery is still nil, but LocationManager.locationManager(manager:didUpdateLocations:) was already called. The update will not be processed.")
            
            return
        }
        
        if let newLocation = locations.last {
            print("Location of the local player was updated: \(String(describing: newLocation))")
            
            lastKnownLocation = newLocation
            
            // Post location to firebase.
            self.rdbRef.child(databasePath).child(session.user!.uid).setValue([
                "playsAs": String(session.user!.playsAs!.rawValue),
                "lastTimeOnline": ServerValue.timestamp()
            ])
            geoFire.setLocation(lastKnownLocation!, forKey: session.user!.uid){ (error) in
                if (error != nil) {
                    print("An error occured: \(String(describing: error))")
                } else {
                    print("Saved new location of the local player to firebase successfully.")
                }
            }
            
            // Update circleQuery.
            self.circleQuery!.center = self.lastKnownLocation!
  
        }
        
    }

    func locationManager(_ manager: CLLocationManager, didChangeAuthorization status: CLAuthorizationStatus) {
        if status == .authorizedWhenInUse {
            manager.startUpdatingLocation()
        }
    }
    
    // MARK: gfEventProcessors
    
    typealias gfEventProcessor = (String, CLLocation) -> ()
    
    func keyEnteredProcessor(key enteredUid: String, enteredUserLocation: CLLocation) -> () {
        
        if enteredUid == session.user!.uid {
            
            print("The .keyEntered fired on the local user, nothing to do.")
            
        } else {
            print("Player with uid (key) '\(String(describing: enteredUid))' entered the search area and is at location '\(String(describing: enteredUserLocation))'")
            
            rdbRef.child(databasePath + "/" + enteredUid + "/playsAs").observeSingleEvent(of: .value, with: { (snapshot) in
                guard let stringUserPlaysAs = snapshot.value as? String else {
                    print ("Warning: playAs of a nearby online player stored in the realtime database seems to be absent. This .keyEnteredEvent will not be processed.")
                    return
                }
                
                let userPlaysAs: PlayAs?

                switch stringUserPlaysAs {
                case "human": userPlaysAs = .human
                case "zombie": userPlaysAs = .zombie
                default: userPlaysAs = nil
                }

                guard userPlaysAs != nil else {
                    print("Warning: Invalid player type when initializing a PlayAs instance:" + stringUserPlaysAs + ". Therefore no marker will be placed for this player." )
                    return
                }
                
                let enteredUser = User(uid: enteredUid, displayName: nil, email: nil, location: enteredUserLocation, playsAs: userPlaysAs)
                let distanceToUser = self.lastKnownLocation!.distance(from: enteredUserLocation)
                
                if self.localUserCollidedWithAnotherPlayerType(anotherPlayer: enteredUser) {
                    print("Collision of different types of players happened: Local user \(self.session.user!.uid) (\(self.session.user!.playsAs!)) and another user \(enteredUser.uid) (\(enteredUser.playsAs!)).")
                    self.zombieCollidedWithHuman = true
                }
        
                
                //self.nearbyPlayers.updateValue(distanceToUser, forKey: enteredUser)
                self.nearbyPlayers[enteredUser.uid] = (enteredUser, distanceToUser)
                
            }) { (error) in
                print(error.localizedDescription)
            }

            
        }
        
        
    }
    
    func keyMovedProcessor(key movedUid: String, movedUserLocation: CLLocation) -> () {
        
        if movedUid == session.user!.uid {
        
            print("The .keyMoved fired on the local user, nothing to do.")
            
        } else {
            
            print("Player with uid (key) '\(String(describing: movedUid))' moved in the search area and is at location '\(String(describing: movedUserLocation))'")
            
            rdbRef.child(databasePath + "/" + movedUid + "/playsAs").observeSingleEvent(of: .value, with: { (snapshot) in
                guard let stringUserPlaysAs = snapshot.value as? String else {
                    print ("Warning: playAs of a nearby online player stored in the realtime database seems to be absent. This .keyMovedEvent will not be processed.")
                    return
                }
                
                let userPlaysAs: PlayAs?

                switch stringUserPlaysAs {
                case "human": userPlaysAs = .human
                case "zombie": userPlaysAs = .zombie
                default: userPlaysAs = nil
                }

                guard userPlaysAs != nil else {
                    print("Warning: Invalid player type when initializing a PlayAs instance:" + stringUserPlaysAs + ". Therefore no marker will be placed for this player." )
                    return
                }
                
                let movedUser = User(uid: movedUid, displayName: nil, email: nil, location: movedUserLocation, playsAs: userPlaysAs)
                let distanceToUser = self.lastKnownLocation!.distance(from: movedUserLocation)
                
                
                if self.localUserCollidedWithAnotherPlayerType(anotherPlayer: movedUser) {
                    print("Collision of different types of players happened: Local user \(self.session.user!.uid) (\(self.session.user!.playsAs!)) and another user \(movedUser.uid) (\(movedUser.playsAs!)).")
                    self.zombieCollidedWithHuman = true
                }

                //self.nearbyPlayers.updateValue(distanceToUser, forKey: movedUser)
                self.nearbyPlayers[movedUser.uid] = (movedUser, distanceToUser)
                
                print("Updated location of the moving nearby user \(movedUser.uid).")
            }) { (error) in
                print(error.localizedDescription)
            }
        
        }

        
    }
    
    func keyExitedProcessor(key uid: String, exitedUserLocation: CLLocation) -> () {
        print("Player with uid (key) '\(String(describing: uid))' exited the search area and is at location '\(String(describing: exitedUserLocation))'")

        let exitedUser = User(uid: uid, displayName: nil, email: nil, location: exitedUserLocation)

        self.nearbyPlayers.removeValue(forKey: exitedUser.uid)
    }
    
    // MARK: Collision detection
    
    func localUserCollided(withUserAtLocation otherUsersLocation: CLLocation ) -> Bool {
        let distanceToUser = lastKnownLocation!.distance(from: otherUsersLocation)
        
        return distanceToUser.isLessThanOrEqualTo(collisionDistance)
    }
    
    func localUserCollidedWithAnotherPlayerType(anotherPlayer: User) -> Bool {
        return (localUserCollided(withUserAtLocation: anotherPlayer.location!)
            && session.user!.playsAs! != anotherPlayer.playsAs!)
    }
    
}
