source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hunger' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hunger
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
#  pod 'Firebase/Firestore'
  pod 'Fabric'
  pod 'Crashlytics'
#  pod 'Firebase/Performance'
#  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  pod 'GoogleMaps'
  pod 'GooglePlaces'

  pod 'GeoFire', '~> 3.0'

  target 'HungerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HungerUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
